  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: ENV['DATABASE']
  pool: 5
  username: ENV['POST_USERNAME']
  password: ENV['POST_SECERT_KEY']
